language: python
python:
  - "3.6"
services:
  - sqlite
env:
  -DJANGO=2.1 DB=sqlite
# command to install dependencies
install:
  - pip install -r requirements.txt
script:
  - python manage.py makemigrations
  - python manage.py migrate
  - python manage.py test
# publish coverage only after a successful build
after_success:
  - codecov
notifications:
  email: false
branches:
  only:
    - master
    - develop